# use this for standard usage

version: '3'

services:
  bot:
    image: cyberinfohq/integer:latest
    restart: always
    environment:
      - DATABASE_URI=$DATABASE_URI
      - WEBSOCKET_INTERNAL_URI=ws://manager
      - BOT_TOKEN=$BOT_TOKEN
    volumes:
      - ./logs/countr:/app/logs
    depends_on:
#      - db
      - manager
  manager:
    image: cyberinfohq/integer:latest
    restart: always
    command: "start:manager"
    environment:
      - DATABASE_URI=$DATABASE_URI
      - WEBSOCKET_INTERNAL_PORT=80
    volumes:
      - ./logs/manager:/app/logs
    ports:
      - $API_PORT:$API_PORT
    depends_on:
      - db
  db:
    image: mongo:4@sha256:033255f596fb18ee947fabef1377f666f96ff0c0328242a7ff219c284537a76f
    restart: always
    volumes:
      - ./database:/data/db
