# this is for the premium bot.

version: '3'

services:
  cluster0:
    build: .
    restart: always
    volumes:
      - ./logs/countr-cluster0:/app/logs
    environment:
      - IS_PREMIUM=true
      - ACCESS_ENABLED=true
    depends_on:
      - manager
  manager:
    build: .
    restart: always
    command: "start:manager"
    volumes:
      - ./logs/manager:/app/logs
